spring:
  cloud:
    azure:
      keyvault:
        secret:
          property-sources[0]:
            endpoint: ${AZURE_KEY_VAULT_ENDPOINT} # environment variable
      storage:
        blob:
          account-name: ${AZURE_STORAGE_ACCOUNT_NAME} # environment variable
  datasource:
    url: ${datasource-url} # secret from Azure Key Vault
    username: ${datasource-username} # secret from Azure Key Vault
    password: ${datasource-password} # secret from Azure Key Vault
  jpa:
    hibernate:
      ddl-auto: none # Turn off the DDL auto generation.
  data:
    redis:
      host: ${redis-host} # secret from Azure Key Vault
      port: 6380
      username: ${redis-username} # secret from Azure Key Vault
      ssl:
        enabled: true
      azure:
        passwordless-enabled: true

ai:
  meta-llama:
    endpoint: ${AI_META_LLAMA_ENDPOINT:https://api-inference.huggingface.co/models/meta-llama/Meta-Llama-3-8B-Instruct/v1/chat/completions} # environment variable with a default value
    api-key: ${ai-hugging-face-api-key:your-api-key} # secret from Azure Key Vault